# -*- coding: utf-8 -*-
"""cubegpt3_solve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuHVrBK91fx4x5ENxIFXiNZI-27rmxgS
"""

# !pip install git+https://github.com/KellerJordan/Muon

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import torch
from torch import nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.data import WeightedRandomSampler
import torch.nn.functional as F
import random
from itertools import permutations, product


import time
import matplotlib.pyplot as plt
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

print(torch.__version__, torch.cuda.get_device_name(0)); print(torch.zeros(1).cuda())

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

from google.colab import drive
drive.mount('/content/drive')

import json
f = open("/content/drive/MyDrive/cube_utils.json")
tables = json.load(f)
f.close()

solved_string = "WWWWWWWWWOOOOOOOOOGGGGGGGGGRRRRRRRRRBBBBBBBBBYYYYYYYYY"
SOLVED_COLORS = ["W", "O", "G", "R", "B", "Y"]
pos_idx = eval(tables["pos_idx"])
pos_face_idx = eval(tables["pos_face_idx"])
color_str_tensor_idx = tables["color_str_tensor_idx"]
color_str_orientation = tables["color_str_orientation"]
move_map = tables["move_map"]

def get_colors_str_by_pos(cube_string, position):
    return "".join([cube_string[i] for i in pos_face_idx[position]])

def string_to_tokens(cube_string):
    tokens_tensor = torch.zeros((20, 2), dtype=torch.int32)

    orien_idx_to_token = {
        0: 0,
        3: 1,
        4: 2,
        1: 0,
        2: 1,
        5: 2,
    }

    edge_orientations = 2
    corner_orientations = 3

    for pos, position_idx in pos_idx.items():
        color_str = get_colors_str_by_pos(cube_string, pos)
        is_edge = len(color_str) == 2

        piece_idx = color_str_tensor_idx[color_str]
        orientation_idx = color_str_orientation[color_str]

        if is_edge:
            placement_token = position_idx * edge_orientations + orientation_idx
        else:
            orientation_idx = orien_idx_to_token[orientation_idx]
            placement_token = position_idx * corner_orientations + orientation_idx
            placement_token += 24

        tokens_tensor[piece_idx][0] = piece_idx # redundant, but makes code more consistent.
        tokens_tensor[piece_idx][1] = placement_token

    return tokens_tensor

def string_to_tensor(cube_string):
    cube_tensor = torch.zeros((20, 14), dtype=torch.float32)

    for pos, pos_value in pos_idx.items():
        color_str = get_colors_str_by_pos(cube_string, pos)
        is_edge = len(color_str) == 2

        tensor_idx = color_str_tensor_idx[color_str]
        orientation_value = color_str_orientation[color_str]

        cube_tensor[tensor_idx][pos_value] = 1
        if is_edge:
            cube_tensor[tensor_idx][12 + orientation_value] = 1
        else:
            cube_tensor[tensor_idx][8 + orientation_value] = 1

    return cube_tensor

def rotate_string(cube_str, move=None):
    """Fast rotate function for cube strings."""
    return "".join([cube_str[i] for i in move_map[move]])

class CubeState:
    # moves[move_class][move_type]
    # move_class --> U, U', U2, D, D', D2
    # move_type --> U, U', U2
    # when scrambling:
    # maximum 2 moves with same move_class in a row
    # maximum 1 move with same move_class, move_type in a row
    moves = [
        [["U", "U'", "U2"], ["D", "D'", "D2"]],
        [["L", "L'", "L2"], ["R", "R'", "R2"]],
        [["F", "F'", "F2"], ["B", "B'", "B2"]],
             ]

    def __init__(self, cube_string : str = solved_string,
                 prev_state = None,
                 prev_move = None,
                 prev_move_class = None,
                 prev_move_type = None
                 ):
        self.cube_string = cube_string
        self.prev_state = prev_state
        self.prev_move = prev_move
        self.prev_move_class = prev_move_class
        self.prev_move_type = prev_move_type

        self.prev2_move_class = None
        if prev_state:
            self.prev2_move_class = prev_state.prev_move_class

    def forget(self):
        """Forget this Cube's history (for fair solving)."""
        self.prev_state = None
        self.prev_move = None
        self.prev_move_class = None
        self.prev_move_type = None
        self.prev2_move_class = None

    def get_tensor(self):
        return string_to_tensor(self.cube_string)

    def get_tokens(self):
        return string_to_tokens(self.cube_string)

    def get_allowed_moves(self):
        # (move_class, move_type, move_index)
        for move_class in range(len(CubeState.moves)):
            # Skip if this would be the 3rd consecutive move from the same move class
            if (move_class == self.prev_move_class and
                move_class == self.prev2_move_class):
                continue

            for move_type in range(len(CubeState.moves[move_class])):
                # Skip if this would be the 2nd consecutive move from the same move type
                if (move_class == self.prev_move_class and
                    move_type == self.prev_move_type):
                    continue

                for move_index in range(len(CubeState.moves[move_class][move_type])):
                    yield (move_class, move_type, move_index)

    def get_child(self, move_class, move_type, move_index):
        """Get child state with given move_class, move_type, and move_index"""
        move = CubeState.moves[move_class][move_type][move_index]
        return CubeState(
            cube_string=rotate_string(self.cube_string, move),
            prev_state=self,
            prev_move=move,
            prev_move_class=move_class,
            prev_move_type=move_type
        )

    def get_random_child(self):
        allowed_moves = list(self.get_allowed_moves())
        move_class, move_type, move_index = allowed_moves[np.random.randint(len(allowed_moves))]
        return self.get_child(move_class, move_type, move_index)

    def get_children(self):
        """Generate all valid child states following the move constraints."""
        children = []
        for (move_class, move_type, move_index) in self.get_allowed_moves():
            children.append(self.get_child(move_class, move_type, move_index))
        return children

    def get_child_dict(self):
        """Generate a dictionary with all child constraints. Does not consider move constraints."""
        children = {}
        for move_class in range(len(CubeState.moves)):
            for move_type in range(len(CubeState.moves[move_class])):
                for move_index in range(len(CubeState.moves[move_class][move_type])):
                    move = CubeState.moves[move_class][move_type][move_index]
                    children[move] = self.get_child(move_class, move_type, move_index)
        return children

INCLUDE_MIRRORS = True   # True -> 48 symmetries, False -> 24 (rotations only)

# ----------------------------------------------------------------------------
# STEP 0 — Basic facts about the 54-character cube string.
# Facelets 0-8 are face 0, facelets 9-17 are face 1, and so on.
# ----------------------------------------------------------------------------
NUM_FACES = 6
NUM_FACELETS = 54

def face_of_facelet(facelet):
    return facelet // 9

CENTER_FACELET = [9 * face + 4 for face in range(NUM_FACES)]
SOLVED_COLOR = [solved_string[CENTER_FACELET[face]] for face in range(NUM_FACES)]
# SOLVED_COLOR == ['W', 'O', 'G', 'R', 'B', 'Y']

# ----------------------------------------------------------------------------
# STEP 1 — Which direction does each face point?
#
# Cubie positions are (x, y, z) coordinates in {0,1,2}^3. A sticker lies on one
# of the six outer planes of the cube; we describe a plane by its outward
# normal, e.g. (-1, 0, 0) means the x=0 plane. To find each face's normal,
# intersect the candidate planes over every cubie carrying a sticker of that
# face — only the true normal survives.
# ----------------------------------------------------------------------------
def outward_normals(position):
    """The outer planes touched by the cubie at this position."""
    normals = set()
    for axis in range(3):
        if position[axis] == 0:
            normal = [0, 0, 0]; normal[axis] = -1
            normals.add(tuple(normal))
        if position[axis] == 2:
            normal = [0, 0, 0]; normal[axis] = +1
            normals.add(tuple(normal))
    return normals

candidate_normals = [None] * NUM_FACES
for position, facelets in pos_face_idx.items():
    for facelet in facelets:
        face = face_of_facelet(facelet)
        if candidate_normals[face] is None:
            candidate_normals[face] = outward_normals(position)
        else:
            candidate_normals[face] &= outward_normals(position)

assert all(len(candidates) == 1 for candidates in candidate_normals)
FACE_NORMAL = [candidates.pop() for candidates in candidate_normals]

# ----------------------------------------------------------------------------
# STEP 2 — A coordinate system for every sticker.
#
# Every sticker is uniquely identified by (cubie position, face normal).
# Centers get pseudo-positions like (0, 1, 1) so all 54 facelets are covered.
# ----------------------------------------------------------------------------
FACELET_AT = {}   # (position, normal) -> facelet index
for position, facelets in pos_face_idx.items():
    for facelet in facelets:
        normal = FACE_NORMAL[face_of_facelet(facelet)]
        FACELET_AT[(tuple(position), normal)] = facelet

for face in range(NUM_FACES):
    normal = FACE_NORMAL[face]
    center_position = (1 + normal[0], 1 + normal[1], 1 + normal[2])
    FACELET_AT[(center_position, normal)] = CENTER_FACELET[face]

assert len(FACELET_AT) == NUM_FACELETS

# ----------------------------------------------------------------------------
# STEP 3 — The whole-cube symmetries as 3x3 matrices.
#
# The rotations of a cube are exactly the signed permutation matrices with
# determinant +1 (24 of them). Determinant -1 adds the mirror images (48
# total). Matrices act on positions about the cube's center (1, 1, 1).
# ----------------------------------------------------------------------------
symmetry_matrices = []
for axis_permutation in permutations(range(3)):
    for signs in product((+1, -1), repeat=3):
        matrix = np.zeros((3, 3), dtype=int)
        for row in range(3):
            matrix[row, axis_permutation[row]] = signs[row]
        is_rotation = round(np.linalg.det(matrix)) == 1
        if is_rotation or INCLUDE_MIRRORS:
            symmetry_matrices.append(matrix)

def transform_position(matrix, position):
    centered = np.array(position) - 1
    return tuple(matrix @ centered + 1)

def transform_normal(matrix, normal):
    return tuple(matrix @ np.array(normal))

# ----------------------------------------------------------------------------
# STEP 4 — Compile each matrix into fast string operations.
#
# Each symmetry becomes:
#   gather  : sticker permutation, same convention as move_map
#             (new_string[i] = old_string[gather[i]])
#   recolor : str.translate table that repaints stickers so centers are
#             standard again. It depends only on the symmetry, not the state,
#             because moves never displace centers.
# ----------------------------------------------------------------------------
SYMMETRIES = []
for matrix in symmetry_matrices:
    gather = [None] * NUM_FACELETS
    for (position, normal), facelet in FACELET_AT.items():
        new_position = transform_position(matrix, position)
        new_normal = transform_normal(matrix, normal)
        new_facelet = FACELET_AT[(new_position, new_normal)]
        gather[new_facelet] = facelet

    rotated_solved = "".join(solved_string[gather[i]] for i in range(NUM_FACELETS))
    recolor_map = {}
    for face in range(NUM_FACES):
        color_after_rotation = rotated_solved[CENTER_FACELET[face]]
        recolor_map[color_after_rotation] = SOLVED_COLOR[face]
    recolor = str.maketrans(recolor_map)

    SYMMETRIES.append((gather, recolor))

assert len(SYMMETRIES) == (48 if INCLUDE_MIRRORS else 24)

# ----------------------------------------------------------------------------
# STEP 5 — Apply a symmetry; canonicalize over all of them.
# ----------------------------------------------------------------------------
def apply_symmetry(cube_string, gather, recolor):
    permuted = "".join(cube_string[gather[i]] for i in range(NUM_FACELETS))
    return permuted.translate(recolor)

def canonicalize(cube_string):
    variants = [apply_symmetry(cube_string, gather, recolor)
                for gather, recolor in SYMMETRIES]
    return min(variants)

# ----------------------------------------------------------------------------
# STEP 6 — Optional extra factor of 2: distance(s) == distance(s_inverse).
#
# To invert a state: every sticker's color tells you which face it belongs to,
# so summing the face normals of a cubie's colors gives its home position.
# Send each sticker home, and record at the home facelet the color of the slot
# the sticker came from.
# ----------------------------------------------------------------------------
def invert_string(cube_string):
    result = [None] * NUM_FACELETS
    for face in range(NUM_FACES):
        result[CENTER_FACELET[face]] = SOLVED_COLOR[face]

    for position, facelets in pos_face_idx.items():
        home_position = np.array([1, 1, 1])
        for facelet in facelets:
            color = cube_string[facelet]
            home_position += np.array(FACE_NORMAL[SOLVED_COLOR.index(color)])
        home_position = tuple(home_position)

        for facelet in facelets:
            color = cube_string[facelet]
            home_facelet = FACELET_AT[(home_position,
                                       FACE_NORMAL[SOLVED_COLOR.index(color)])]
            result[home_facelet] = SOLVED_COLOR[face_of_facelet(facelet)]

    return "".join(result)

def canonicalize_full(cube_string):
    return min(canonicalize(cube_string), canonicalize(invert_string(cube_string)))

# ----------------------------------------------------------------------------
# STEP 7 — Self-tests. Run these once; they catch every plausible bug.
# ----------------------------------------------------------------------------
ALL_MOVES = [move for move in move_map if move != "null"]

# Test 1: every symmetry maps the solved state to itself.
for gather, recolor in SYMMETRIES:
    assert apply_symmetry(solved_string, gather, recolor) == solved_string

# A random scramble to test on.
state = solved_string
for _ in range(30):
    state = rotate_string(state, random.choice(ALL_MOVES))

# Test 2: each symmetry maps the move set onto itself — i.e. for every move m
# there is a move m2 with  sym(m(state)) == m2(sym(state)). This is precisely
# the property that makes move-distance symmetry-invariant.
for gather, recolor in SYMMETRIES:
    state_sym = apply_symmetry(state, gather, recolor)
    for move in ALL_MOVES:
        target = apply_symmetry(rotate_string(state, move), gather, recolor)
        assert any(rotate_string(state_sym, move2) == target
                   for move2 in ALL_MOVES)

# Test 3: canonicalize is constant on a symmetry family.
for gather, recolor in SYMMETRIES:
    assert canonicalize(apply_symmetry(state, gather, recolor)) == canonicalize(state)

# Test 4: inversion behaves (U inverts to U', and canon_full absorbs inversion).
assert invert_string(rotate_string(solved_string, "U")) == rotate_string(solved_string, "U'")
assert canonicalize_full(invert_string(state)) == canonicalize_full(state)

print("all symmetry tests passed")

# ============================================================================
# GPU data generation for CubeGPT.  (Paste as one cell, AFTER the cell that
# builds SYMMETRIES / FACE_NORMAL / FACELET_AT, since tables bootstrap there.)
#
# Representation: a state is a (54,) int64 tensor of color indices 0..5
# (W O G R B Y); a batch is (B, 54). A move or symmetry is a precomputed
# gather row (new[i] = old[gather[i]]), so one torch.gather advances the
# ENTIRE batch by one move. Scrambling = ~20 gathers total, tokenization and
# canonicalization = a few lookup-table gathers. No Python per-sample loops,
# no strings, no CPU<->GPU transfers.
#
# Verified bit-exact against the string implementation:
#   - states_to_tokens  == string_to_tokens
#   - move gathers      == rotate_string for all 18 moves
#   - canonicalize_*    == canonicalize / canonicalize_full
#   - invert_batch      == invert_string
#   - scramble respects get_allowed_moves constraints with the same
#     uniform-over-allowed distribution, and replaying its recorded moves
#     through rotate_string reproduces its states.
# ============================================================================

class CubeTables:
    """All constant tensors, built once and moved to the device once."""

    def __init__(self, device):
        self.device = device
        COLOR_TO_IDX = {c: i for i, c in enumerate(SOLVED_COLOR)}   # W O G R B Y -> 0..5

        def t(arr, dtype=torch.int64):
            return torch.as_tensor(np.asarray(arr), dtype=dtype, device=device)

        # ----- states -------------------------------------------------------
        self.SOLVED = t([COLOR_TO_IDX[c] for c in solved_string])            # (54,)

        # ----- moves: flat id = (axis*2 + side)*3 + variant, null = 18 ------
        move_names = [CubeState.moves[a][s][v]
                      for a in range(3) for s in range(2) for v in range(3)]
        move_names.append("null")
        self.MOVE_NAMES = move_names
        self.MOVE_GATHER = t([move_map[m] for m in move_names])              # (19, 54)
        self.NULL_MOVE = 18
        ids = torch.arange(18, device=device)
        self.MOVE_AXIS = ids // 6                                            # 0..2  (move_class)
        self.MOVE_FACE = ids // 3                                            # 0..5  (class*2+type)

        # ----- tokenization tables ------------------------------------------
        edge_pos = sorted([p for p in pos_face_idx if len(pos_face_idx[p]) == 2],
                          key=lambda p: pos_idx[p])
        corner_pos = sorted([p for p in pos_face_idx if len(pos_face_idx[p]) == 3],
                            key=lambda p: pos_idx[p])
        self.EDGE_FACELETS = t([pos_face_idx[p] for p in edge_pos])          # (12, 2)
        self.CORNER_FACELETS = t([pos_face_idx[p] for p in corner_pos])      # (8, 3)
        self.EDGE_POS_VALUE = t([pos_idx[p] for p in edge_pos])              # (12,)
        self.CORNER_POS_VALUE = t([pos_idx[p] for p in corner_pos])          # (8,)

        # cubie "color code" (base-6 packed colors) -> piece id / orientation
        orien_idx_to_token = {0: 0, 3: 1, 4: 2, 1: 0, 2: 1, 5: 2}
        epiece = np.zeros(36, dtype=np.int64);  eorient = np.zeros(36, dtype=np.int64)
        cpiece = np.zeros(216, dtype=np.int64); corient = np.zeros(216, dtype=np.int64)
        for cs, piece in color_str_tensor_idx.items():
            idxs = [COLOR_TO_IDX[c] for c in cs]
            if len(cs) == 2:
                code = idxs[0] * 6 + idxs[1]
                epiece[code] = piece
                eorient[code] = color_str_orientation[cs]
            else:
                code = idxs[0] * 36 + idxs[1] * 6 + idxs[2]
                cpiece[code] = piece
                corient[code] = orien_idx_to_token[color_str_orientation[cs]]
        self.EDGE_PIECE = t(epiece);   self.EDGE_ORIENT = t(eorient)
        self.CORNER_PIECE = t(cpiece); self.CORNER_ORIENT = t(corient)

        # ----- symmetries (from the canonicalization cell) -------------------
        self.SYM_GATHER = t([g for g, _ in SYMMETRIES])                      # (48, 54)
        self.SYM_RECOLOR = t([[COLOR_TO_IDX[c.translate(trans)] for c in SOLVED_COLOR]
                              for _, trans in SYMMETRIES])                   # (48, 6)

        # lexicographic keys: 54 base-6 digits packed into 3 int64 chunks of 18.
        # Compared in alphabetical order of the color letters, so the chosen
        # representative matches the string implementation exactly.
        self.POW6 = t(6 ** np.arange(17, -1, -1, dtype=np.int64))            # (18,)
        self.CMP_RANK = t([sorted(SOLVED_COLOR).index(c) for c in SOLVED_COLOR])

        # ----- inversion: per slot, per cubie code -> home facelet per sticker
        einv = np.zeros((12, 36, 2), dtype=np.int64)
        cinv = np.zeros((8, 216, 3), dtype=np.int64)
        for cs in color_str_tensor_idx:
            idxs = [COLOR_TO_IDX[c] for c in cs]
            home = np.array([1, 1, 1])
            for ci in idxs:
                home += np.array(FACE_NORMAL[ci])        # color index == face index
            home = tuple(home)
            targets = [FACELET_AT[(home, FACE_NORMAL[ci])] for ci in idxs]
            if len(cs) == 2:
                einv[:, idxs[0] * 6 + idxs[1], :] = targets
            else:
                cinv[:, idxs[0] * 36 + idxs[1] * 6 + idxs[2], :] = targets
        self.EDGE_INV_TARGET = t(einv)                                       # (12, 36, 2)
        self.CORNER_INV_TARGET = t(cinv)                                     # (8, 216, 3)
        # color written at the home facelet = solved color of the source slot
        self.EDGE_SRC_COLOR = t([[face_of_facelet(i) for i in pos_face_idx[p]] for p in edge_pos])
        self.CORNER_SRC_COLOR = t([[face_of_facelet(i) for i in pos_face_idx[p]] for p in corner_pos])


# ----------------------------------------------------------------------------
# Scrambling. Per-sample lengths handled by feeding finished samples "null".
# Constraints replicate CubeState.get_allowed_moves exactly:
#   - never the same face as the previous move
#   - never the same axis three times in a row
# with the move drawn uniformly among allowed ones (rand + masked argmax).
# ----------------------------------------------------------------------------
def scramble_batch(T, batch_size, scramble_limit=21, lengths=None, return_trajectory=False):
    dev = T.device
    if lengths is None:
        lengths = torch.randint(0, scramble_limit, (batch_size,), device=dev)
    max_steps = scramble_limit - 1

    states = T.SOLVED.unsqueeze(0).expand(batch_size, 54).clone()
    prev_axis = torch.full((batch_size,), -1, dtype=torch.int64, device=dev)
    prev2_axis = torch.full((batch_size,), -2, dtype=torch.int64, device=dev)
    prev_face = torch.full((batch_size,), -1, dtype=torch.int64, device=dev)

    trajectory = [states] if return_trajectory else None

    for step in range(max_steps):
        active = step < lengths                                              # (B,)

        banned = T.MOVE_FACE.unsqueeze(0) == prev_face.unsqueeze(1)          # same face again
        banned |= ((T.MOVE_AXIS.unsqueeze(0) == prev_axis.unsqueeze(1))
                   & (prev_axis == prev2_axis).unsqueeze(1))                 # 3rd time same axis
        scores = torch.rand(batch_size, 18, device=dev).masked_fill(banned, -1.0)
        choice = scores.argmax(dim=1)                                        # uniform over allowed

        applied = torch.where(active, choice, torch.full_like(choice, T.NULL_MOVE))
        states = torch.gather(states, 1, T.MOVE_GATHER[applied])

        prev2_axis = torch.where(active, prev_axis, prev2_axis)
        prev_face = torch.where(active, T.MOVE_FACE[choice], prev_face)
        prev_axis = torch.where(active, T.MOVE_AXIS[choice], prev_axis)

        if return_trajectory:
            trajectory.append(states)

    if return_trajectory:
        return torch.stack(trajectory, dim=1), lengths                       # (B, scramble_limit, 54)
    return states, lengths


# ----------------------------------------------------------------------------
# Tokenization: (B, 54) -> (B, 20, 2), identical to string_to_tokens.
# Each cubie's colors pack into a base-6 code; tiny LUTs map code -> piece id
# and orientation; placements scatter into rows ordered by piece id.
# ----------------------------------------------------------------------------
def states_to_tokens(T, states):
    B = states.shape[0]

    ec = states[:, T.EDGE_FACELETS]                                          # (B, 12, 2)
    ecode = ec[..., 0] * 6 + ec[..., 1]
    epiece = T.EDGE_PIECE[ecode]                                             # (B, 12) -> 0..11
    eplace = T.EDGE_POS_VALUE.unsqueeze(0) * 2 + T.EDGE_ORIENT[ecode]

    cc = states[:, T.CORNER_FACELETS]                                        # (B, 8, 3)
    ccode = cc[..., 0] * 36 + cc[..., 1] * 6 + cc[..., 2]
    cpiece = T.CORNER_PIECE[ccode]                                           # (B, 8) -> 12..19
    cplace = T.CORNER_POS_VALUE.unsqueeze(0) * 3 + T.CORNER_ORIENT[ccode] + 24

    placements = torch.empty(B, 20, dtype=torch.int64, device=T.device)
    placements.scatter_(1, epiece, eplace)
    placements.scatter_(1, cpiece, cplace)

    piece_ids = torch.arange(20, device=T.device).unsqueeze(0).expand(B, 20)
    return torch.stack([piece_ids, placements], dim=2)                       # (B, 20, 2)


# ----------------------------------------------------------------------------
# Canonicalization: one gather applies all 48 symmetries; a 3-stage masked
# argmin picks the lexicographically smallest variant per sample.
# ----------------------------------------------------------------------------
def _lex_argmin(T, variants):
    """variants: (B, K, 54) -> index (B,) of the lexicographically smallest row."""
    digits = T.CMP_RANK[variants].view(variants.shape[0], variants.shape[1], 3, 18)
    keys = (digits * T.POW6).sum(dim=3)                                      # (B, K, 3)
    BIG = torch.tensor(2 ** 62, dtype=torch.int64, device=T.device)
    alive = torch.ones(variants.shape[:2], dtype=torch.bool, device=T.device)
    for j in range(3):
        kj = torch.where(alive, keys[..., j], BIG)
        alive &= kj.eq(kj.min(dim=1, keepdim=True).values)
    return alive.to(torch.int64).argmax(dim=1)

def apply_all_symmetries(T, states):
    variants = states[:, T.SYM_GATHER]                                       # (B, 48, 54)
    recolor = T.SYM_RECOLOR.unsqueeze(0).expand(states.shape[0], -1, -1)
    return torch.gather(recolor, 2, variants)

def canonicalize_batch(T, states):
    variants = apply_all_symmetries(T, states)
    best = _lex_argmin(T, variants)
    return variants[torch.arange(states.shape[0], device=T.device), best]

def invert_batch(T, states):
    """The inverse state of every state in the batch (distance-preserving)."""
    B = states.shape[0]
    result = T.SOLVED.unsqueeze(0).expand(B, 54).clone()    # centers already correct

    ec = states[:, T.EDGE_FACELETS]
    ecode = ec[..., 0] * 6 + ec[..., 1]
    etgt = T.EDGE_INV_TARGET[torch.arange(12, device=T.device), ecode]       # (B, 12, 2)
    result.scatter_(1, etgt.reshape(B, 24), T.EDGE_SRC_COLOR.reshape(1, 24).expand(B, 24))

    cc = states[:, T.CORNER_FACELETS]
    ccode = cc[..., 0] * 36 + cc[..., 1] * 6 + cc[..., 2]
    ctgt = T.CORNER_INV_TARGET[torch.arange(8, device=T.device), ccode]      # (B, 8, 3)
    result.scatter_(1, ctgt.reshape(B, 24), T.CORNER_SRC_COLOR.reshape(1, 24).expand(B, 24))
    return result

def canonicalize_full_batch(T, states):
    """min over 48 symmetries x {state, inverse} = 96 variants."""
    v = torch.cat([apply_all_symmetries(T, states),
                   apply_all_symmetries(T, invert_batch(T, states))], dim=1)
    best = _lex_argmin(T, v)
    return v[torch.arange(states.shape[0], device=T.device), best]


# ----------------------------------------------------------------------------
# Drop-in replacements for generate_batch_ord / generate_path_batch.
# ----------------------------------------------------------------------------
def generate_batch_ord(T, n, scramble_limit=21, canonical=True, full=True):
    states, steps = scramble_batch(T, n, scramble_limit)
    if canonical:
        states = canonicalize_full_batch(T, states) if full else canonicalize_batch(T, states)
    return states_to_tokens(T, states), to_ordinal_targets(steps)

def generate_path_batch(T, k, k_max=21, canonical=True, full=True):
    lengths = torch.full((k,), k_max - 1, dtype=torch.int64, device=T.device)
    traj, _ = scramble_batch(T, k, k_max, lengths=lengths, return_trajectory=True)
    states = traj.reshape(k * k_max, 54)
    steps = torch.arange(k_max, device=T.device).repeat(k)
    if canonical:
        states = canonicalize_full_batch(T, states) if full else canonicalize_batch(T, states)
    return states_to_tokens(T, states), to_ordinal_targets(steps)


# Build once, right after model/device setup:
# T = CubeTables(device)
# ...then in the training loop:
# X, y = generate_batch_ord_gpu(T, batch_size, scramble_limit)

class MultiHeadAttention(nn.Module):
    """
    Computes multi-head attention. Supports nested or padded tensors.

    Args:
        d_model: the residual stream dimension
        n_heads: the number of attn heads, must divide d_model
    """

    def __init__(self, d_model, n_heads, bias=True):
        super().__init__()

        assert d_model % n_heads == 0, "Embedding dim is not divisible by nheads"

        self.bias = bias

        self.n_heads = n_heads
        self.d_head = d_model // n_heads
        self.q_proj = nn.Linear(d_model, d_model, bias=bias)
        self.k_proj = nn.Linear(d_model, d_model, bias=bias)
        self.v_proj = nn.Linear(d_model, d_model, bias=bias)

        self.out_proj = nn.Linear(d_model, d_model, bias=bias)


    def forward(self, x: torch.Tensor,) -> torch.Tensor:
        """
        Args:
            x (torch.Tensor): (B, n_tokens, d_model)
        Returns:
            attn_output (torch.Tensor): output of shape (B, n_tokens, d_model)
        """
        # Step 1. Apply input projection

        query = self.q_proj(x) # (B, n_tokens, d_model)
        key = self.k_proj(x)
        value = self.v_proj(x)

        # (B, n_tokens, d_model) --> (B, n_tokens, n_heads, d_head) --> (B, n_heads, n_tokens, d_head)
        query = query.unflatten(-1, [self.n_heads, self.d_head]).transpose(1, 2)
        key = key.unflatten(-1, [self.n_heads, self.d_head]).transpose(1, 2)
        value = value.unflatten(-1, [self.n_heads, self.d_head]).transpose(1, 2)

        # (B, n_heads, n_tokens, d_head)
        attn_output = F.scaled_dot_product_attention(query, key, value)

        # (B, n_heads, n_tokens, d_head) --> (B, n_tokens, n_heads, d_head) --> (B, n_tokens, d_model)
        attn_output = attn_output.transpose(1, 2).flatten(-2)
        # (B, n_tokens, d_model) --> (B, n_tokens, d_model)
        attn_output = self.out_proj(attn_output)

        return attn_output

class MLPBlock(nn.Module):
    def __init__(
            self,
            d_model,
            d_ffwd,
            bias=True,
            activation=nn.functional.gelu
        ):
        super().__init__()
        self.up_proj = nn.Linear(d_model, d_ffwd, bias)
        self.activation = activation
        self.down_proj = nn.Linear(d_ffwd, d_model, bias)

    def forward(self, x):
        return self.down_proj(self.activation(self.up_proj(x)))

class CubeTransformerLayer(nn.Module):
    def __init__(self, d_model, n_heads, d_ffwd, activation=nn.functional.gelu, bias=True):
        super().__init__()

        self.mha_block = MultiHeadAttention(d_model, n_heads, bias=bias)
        self.mlp_block = MLPBlock(d_model, d_ffwd, bias=bias, activation=activation)

        self.norm1 = nn.LayerNorm(d_model, bias=bias)
        self.norm2 = nn.LayerNorm(d_model, bias=bias)

    def forward(self, x):
        x = x + self.mha_block(x)
        x = self.norm1(x)
        x = x + self.mlp_block(x)
        x = self.norm2(x)
        return x

class CubeTransformer(nn.Module):
    def __init__(self, d_model=256, n_heads=16, d_ffwd=512, n_layers=8, activation=nn.functional.gelu):
        super().__init__()
        self.piece_embed_table = nn.Embedding(20, d_model)
        self.placement_embed_table = nn.Embedding(48, d_model)

        self.stack = nn.Sequential(*[
            CubeTransformerLayer(d_model, n_heads, d_ffwd, activation=activation) for i in range(n_layers)
        ])

        n_tokens = 20
        self.final_linear = nn.Sequential(
            nn.Flatten(),
            nn.LayerNorm(n_tokens*d_model),
            nn.Linear(n_tokens*d_model, 21)
        )

    def forward(self, x):
        B = x.shape[0]

        # x : (B, 20, 2)
        piece_embeddings = self.piece_embed_table(x[:, :, 0]) # (B, 20, d_model)
        placement_embeddings = self.placement_embed_table(x[:, :, 1])
        embeddings = piece_embeddings + placement_embeddings # (B, 20, d_model)

        # feed through transformer
        embeddings = self.stack(embeddings) # (B, 21, d_model)

        # isolate cls and run through linear for final prediction
        return self.final_linear(embeddings) # (B,21)

class MLPBlockGated(nn.Module):
    def __init__(
            self,
            d_model,
            d_ffwd,
            bias=True,
        ):
        super().__init__()
        self.up_proj = nn.Linear(d_model, d_ffwd, bias)
        self.gate_proj = nn.Linear(d_model, d_ffwd, bias)
        self.down_proj = nn.Linear(d_ffwd, d_model, bias)

    def forward(self, x):
        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))

class CubeTransformerLayerGated(nn.Module):
    def __init__(self, d_model, n_heads, d_ffwd, bias=True):
        super().__init__()

        self.mha_block = MultiHeadAttention(d_model, n_heads, bias=bias)
        self.mlp_block = MLPBlockGated(d_model, d_ffwd, bias=bias)

        self.norm1 = nn.LayerNorm(d_model, bias=bias)
        self.norm2 = nn.LayerNorm(d_model, bias=bias)

    def forward(self, x):
        x = x + self.mha_block(x)
        x = self.norm1(x)
        x = x + self.mlp_block(x)
        x = self.norm2(x)
        return x

class CubeTransformerGated(nn.Module):
    def __init__(self, d_model=256, n_heads=16, d_ffwd=512, n_layers=8):
        super().__init__()
        self.piece_embed_table = nn.Embedding(20, d_model)
        self.placement_embed_table = nn.Embedding(48, d_model)

        self.stack = nn.Sequential(*[
            CubeTransformerLayerGated(d_model, n_heads, d_ffwd) for i in range(n_layers)
        ])

        n_tokens = 20
        self.final_linear = nn.Sequential(
            nn.Flatten(),
            nn.LayerNorm(n_tokens*d_model),
            nn.Linear(n_tokens*d_model, 21)
        )

    def forward(self, x):
        B = x.shape[0]

        # x : (B, 20, 2)
        piece_embeddings = self.piece_embed_table(x[:, :, 0]) # (B, 20, d_model)
        placement_embeddings = self.placement_embed_table(x[:, :, 1])
        embeddings = piece_embeddings + placement_embeddings # (B, 20, d_model)

        # feed through transformer
        embeddings = self.stack(embeddings) # (B, 21, d_model)

        # isolate cls and run through linear for final prediction
        return self.final_linear(embeddings) # (B,21)

class MoEBlock(nn.Module):
    """
    DeepSeek-V3-style Mixture-of-Experts FFN with auxiliary-loss-free
    load balancing.

    Routing, per token:
        1. affinity   s_i = sigmoid(w_i . x)          (sigmoid, no bias)
        2. selection  top-k over  s_i + b_i           (bias used ONLY here)
        3. gate value g_i = s_i for the selected experts, normalized over the
                      k selected experts, optionally * routed_scaling_factor

    The per-expert bias b_i is not learned by gradient descent. After each
    optimizer step you call `update_expert_bias()`, which nudges each bias by
    +/- gamma depending on whether the expert was under- or over-loaded in the
    last forward. That is the entire load-balancing mechanism: no aux loss in
    the main objective, no gradient through the bias.
    """

    def __init__(
        self,
        d_model,
        d_ffwd,
        n_experts,
        n_active,
        bias=True,
        gated=True,
        activation=nn.functional.gelu,
        bias_update_speed=1e-3,    # gamma
        routed_scaling_factor=1.0, # V3 uses 2.5; 1.0 is fine for a small model
    ):
        super().__init__()
        assert n_active <= n_experts

        self.n_experts = n_experts
        self.n_active = n_active
        self.bias_update_speed = bias_update_speed
        self.routed_scaling_factor = routed_scaling_factor

        if gated:
            self.experts = nn.ModuleList([
                MLPBlockGated(d_model, d_ffwd, bias=bias)
                for _ in range(n_experts)
            ])
        else:
            self.experts = nn.ModuleList([
                MLPBlock(d_model, d_ffwd, bias=bias, activation=activation)
                for _ in range(n_experts)
            ])

        # router: centroid affinity logits, no bias term
        self.gate = nn.Linear(d_model, n_experts, bias=False)

        # additive routing bias b_i -- a buffer, updated by hand, no grad
        self.register_buffer("expert_bias", torch.zeros(n_experts))
        # token load from the most recent forward, consumed by the bias update
        self.register_buffer("tokens_per_expert", torch.zeros(n_experts))

    def forward(self, x):
        # x: (B, T, d_model) -> (N, d_model)
        B, T, d_model = x.shape
        x = x.reshape(-1, d_model)

        # 1. affinity scores (sigmoid -- V3 changed this from V2's softmax)
        scores = self.gate(x).sigmoid()                        # (N, n_experts)

        # 2. top-k selection on the BIASED scores
        biased = scores + self.expert_bias                     # (N, n_experts)
        topk_idx = biased.topk(self.n_active, dim=-1).indices  # (N, n_active)

        # 3. gate values from the UNBIASED scores, normalized over selected
        topk_scores = scores.gather(-1, topk_idx)              # (N, n_active)

        if self.n_active == 1:
            topk_weights = topk_scores
        else:
            topk_weights = topk_scores / (topk_scores.sum(-1, keepdim=True) + 1e-20)

        topk_weights = topk_weights * self.routed_scaling_factor

        # dispatch: run each expert on the tokens routed to it
        out = torch.zeros_like(x)
        load = torch.zeros(self.n_experts, device=x.device)
        for e, expert in enumerate(self.experts):
            tok, slot = (topk_idx == e).nonzero(as_tuple=True)
            if tok.numel() == 0:
                continue
            w = topk_weights[tok, slot].unsqueeze(-1)          # (n_assigned, 1)
            out.index_add_(0, tok, expert(x[tok]) * w)
            load[e] = tok.numel()

        if self.training:
            self.tokens_per_expert.copy_(load.detach())

        return out.view(B, T, d_model)

    @torch.no_grad()
    def update_expert_bias(self):
        """Call once per step, AFTER optimizer.step()."""
        load = self.tokens_per_expert
        err = load.mean() - load            # >0 under-loaded -> raise bias
        self.expert_bias += self.bias_update_speed * torch.sign(err)

class CubeTransformerLayerMoE(nn.Module):
    def __init__(self, d_model, n_heads, d_ffwd, n_experts, n_active, activation=nn.functional.gelu, bias=True):
        super().__init__()

        self.mha_block = MultiHeadAttention(d_model, n_heads, bias=bias)
        self.mlp_block = MoEBlock(d_model, d_ffwd, n_experts, n_active, bias=bias, activation=activation)

        self.norm1 = nn.LayerNorm(d_model, bias=bias)
        self.norm2 = nn.LayerNorm(d_model, bias=bias)

    def forward(self, x):
        x = x + self.mha_block(x)
        x = self.norm1(x)
        x = x + self.mlp_block(x)
        x = self.norm2(x)
        return x

class CubeTransformerMoE(nn.Module):
    def __init__(self, d_model=256, n_heads=16, d_ffwd=512, n_layers=8, n_experts=4, n_active=1):
        super().__init__()
        self.piece_embed_table = nn.Embedding(20, d_model)
        self.placement_embed_table = nn.Embedding(48, d_model)

        self.n_layers = n_layers

        self.stack = nn.Sequential(*[
            CubeTransformerLayerMoE(d_model, n_heads, d_ffwd, n_experts, n_active) for i in range(n_layers)
        ])

        n_tokens = 20
        self.final_linear = nn.Sequential(
            nn.Flatten(),
            nn.LayerNorm(n_tokens*d_model),
            nn.Linear(n_tokens*d_model, 21)
        )

    def forward(self, x):
        B = x.shape[0]

        # x : (B, 20, 2)
        piece_embeddings = self.piece_embed_table(x[:, :, 0]) # (B, 20, d_model)
        placement_embeddings = self.placement_embed_table(x[:, :, 1])
        embeddings = piece_embeddings + placement_embeddings # (B, 20, d_model)

        # feed through transformer
        embeddings = self.stack(embeddings) # (B, 20, d_model)

        # isolate cls and run through linear for final prediction
        return self.final_linear(embeddings) # (B,21)

    @torch.no_grad()
    def update_expert_bias(self):
        for i in range(self.n_layers):
            self.stack[i].mlp_block.update_expert_bias()

def to_ordinal_targets(y, num_classes=21):
    # y: (B)
    # returns: (B, num_classes - 1)
    # Note: We usually use num_classes - 1 because the 0th state is implicit
    # or you can use num_classes if you want a column for every step.

    # Create a range tensor: [0, 1, 2, ..., 20]
    levels = torch.arange(num_classes).to(device)

    # Compare: (B, 1) > (1, 21) -> (B, 21)
    # This results in 1s where the index <= truth, 0s otherwise
    ordinal_y = (y.view(-1, 1) >= levels).float()
    return ordinal_y

def test_batch(X : torch.Tensor, y : torch.Tensor, model : nn.Module, loss_fn : nn.Module, convert_float=False):
    pred = model(X)
    if convert_float:
        loss = loss_fn(pred, y.float())
    else:
        loss = loss_fn(pred, y)
    total_loss = loss.item() * len(y)
    return total_loss

def train_batch(X : torch.Tensor, y : torch.Tensor, model : nn.Module, loss_fn : nn.Module, optimizer : torch.optim.Optimizer, convert_float=False):
    # Forward pass
    pred = model(X)
    if convert_float:
        loss = loss_fn(pred, y.float())
    else:
        loss = loss_fn(pred, y)
    total_loss = loss.item() * len(y)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Return total loss
    return total_loss

def get_ord_avgs(model, batch):
    logits = model(batch)
    probs = nn.Sigmoid()(logits)
    avgs = torch.sum(probs, dim=1) - 1
    return avgs

def measure_mse(model):
  # MSE
  n_batches = 64
  batch_size = 4096
  sample_size = n_batches * batch_size

  errors_list = []
  total_error = 0

  data_gen_per_epochs = 64
  now = time.time()

  model.eval()
  for i in range(n_batches):
      with torch.no_grad():
          local = i % data_gen_per_epochs
          if local == 0:
              X_big, y_big = generate_batch_ord(table, data_gen_per_epochs * batch_size, scramble_limit=21)
              X_big = X_big.view(data_gen_per_epochs, batch_size, *X_big.shape[1:])
              y_big = y_big.view(data_gen_per_epochs, batch_size, *y_big.shape[1:])
          X = X_big[local]
          y = y_big[local]

          y = torch.sum(y, dim=1) - 1
          avgs = get_ord_avgs(model, X)
          sq_errors = ((avgs - y) ** 2).tolist()
          errors_list.extend(sq_errors)

  mean = np.mean(errors_list)
  std = np.std(errors_list) / np.sqrt(sample_size)

  print(f"{mean} +/- {std} (took {time.time() - now}s)")

def measure_acc(model):
  # For Classification Models
  n_batches = 64
  batch_size = 4096
  tolerance = 3
  total_correct = 0
  sample_size = n_batches * batch_size

  correct_list = []

  data_gen_per_epochs = 64

  now = time.time()
  model.eval()
  for i in range(n_batches):
      with torch.no_grad():
          local = i % data_gen_per_epochs
          if local == 0:
              X_big, y_big = generate_batch_ord(table, data_gen_per_epochs * batch_size, scramble_limit=21)
              X_big = X_big.view(data_gen_per_epochs, batch_size, *X_big.shape[1:])
              y_big = y_big.view(data_gen_per_epochs, batch_size, *y_big.shape[1:])
          X = X_big[local]
          y = y_big[local]

          y = torch.sum(y, dim=1) - 1
          avgs = get_ord_avgs(model, X)
          correct = (torch.abs(avgs - y) <= tolerance).tolist()
          correct_list.extend(correct)

  mean = np.mean(correct_list)
  std = np.std(correct_list) / np.sqrt(sample_size)

  print(f"{mean} +/- {std} (took {time.time() - now}s)")

def cube_string_to_state(T, s):
    color_to_idx = {c: i for i, c in enumerate(SOLVED_COLOR)}
    return torch.tensor([color_to_idx[c] for c in s], dtype=torch.int64, device=T.device)

def state_to_cube_string(T, state_vec):
    return "".join(SOLVED_COLOR[i] for i in state_vec.tolist())


def make_model_scorer(T, model, canonical=True, full=True, eval_batch_size=4096, score_fn=None):
    """Wrap a model into scorer(states)->(M,) predicted distance, lower = closer.
       Default score_fn is the ordinal expected value (sum of sigmoids - 1)."""
    if score_fn is None:
        score_fn = lambda logits: torch.sigmoid(logits).sum(dim=1) - 1.0

    @torch.no_grad()
    def scorer(states):                                   # (M, 54) -> (M,)
        out = torch.empty(states.shape[0], device=states.device)
        for i in range(0, states.shape[0], eval_batch_size):   # chunk to bound memory
            chunk = states[i:i + eval_batch_size]
            if canonical:                                      # must match training!
                chunk = canonicalize_full_batch(T, chunk) if full else canonicalize_batch(T, chunk)
            out[i:i + eval_batch_size] = score_fn(model(states_to_tokens(T, chunk)))
        return out
    return scorer


def _reconstruct(history_moves, history_parents, b, m):
    """Walk parent pointers back to the root; returns move ids root -> solved."""
    moves = [int(m)]
    idx = int(b)
    for L in range(len(history_moves) - 1, -1, -1):
        moves.insert(0, int(history_moves[L][idx]))
        idx = int(history_parents[L][idx])
    return moves

def _build_chain(root_string, move_ids):
    """Rebuild a CubeState linked list so the existing display() works unchanged."""
    state = CubeState(cube_string=root_string)
    for mid in move_ids:
        state = state.get_child(mid // 6, (mid // 3) % 2, mid % 3)
    return state


@torch.no_grad()
def beam_search_gpu(T, model, start, width=100, max_moves=30,
                    scorer=None, canonical=True, full=True,
                    eval_batch_size=4096, score_fn=None, verbose=False):
    """Returns (success, solved_CubeState_or_None, list_of_move_names_or_None).
       `start` may be a CubeState, a cube string, or a (54,) state tensor.
       Pass `scorer` to override model scoring (e.g. an oracle for testing)."""
    dev = T.device
    if scorer is None:
        model.eval()
        scorer = make_model_scorer(T, model, canonical, full, eval_batch_size, score_fn)

    if isinstance(start, CubeState):
        frontier = cube_string_to_state(T, start.cube_string).unsqueeze(0)
    elif isinstance(start, str):
        frontier = cube_string_to_state(T, start).unsqueeze(0)
    else:
        frontier = start.view(1, 54).to(dev)
    root_string = state_to_cube_string(T, frontier[0])

    SOLVED = T.SOLVED
    MOVE18 = T.MOVE_GATHER[:18]                                 # drop the null move
    MOVE_FACE, MOVE_AXIS = T.MOVE_FACE, T.MOVE_AXIS

    if torch.equal(frontier[0], SOLVED):
        return True, _build_chain(root_string, []), []

    B = 1
    prev_face = torch.full((B,), -1, dtype=torch.int64, device=dev)
    prev_axis = torch.full((B,), -1, dtype=torch.int64, device=dev)
    prev2_axis = torch.full((B,), -2, dtype=torch.int64, device=dev)
    history_parents, history_moves = [], []

    for depth in range(max_moves):
        B = frontier.shape[0]
        children = frontier[:, MOVE18]                          # (B, 18, 54)

        # solved among all children, BEFORE the beam cutoff
        is_solved = (children == SOLVED).all(dim=2)             # (B, 18)
        if is_solved.any():
            flat = int(is_solved.reshape(-1).nonzero(as_tuple=False)[0].item())
            moves = _reconstruct(history_moves, history_parents, flat // 18, flat % 18)
            return True, _build_chain(root_string, moves), [T.MOVE_NAMES[m] for m in moves]

        # prune the same moves CubeState.get_children would skip
        banned = (MOVE_FACE.unsqueeze(0) == prev_face.unsqueeze(1))           # same face again
        banned |= ((MOVE_AXIS.unsqueeze(0) == prev_axis.unsqueeze(1))
                   & (prev_axis == prev2_axis).unsqueeze(1))                  # 3rd time same axis
        valid = ~banned                                         # (B, 18)

        child_flat = children.reshape(B * 18, 54)
        scores = scorer(child_flat).masked_fill(~valid.reshape(-1), float('inf'))

        k = min(width, int(valid.sum().item()))
        _, top_idx = torch.topk(scores, k, largest=False)       # k smallest = closest
        parent_idx = top_idx // 18
        move_id = top_idx % 18

        frontier = child_flat[top_idx]                          # (k, 54)
        prev2_axis = prev_axis[parent_idx]                      # parent's axis -> new prev2
        prev_axis = MOVE_AXIS[move_id]
        prev_face = MOVE_FACE[move_id]
        history_parents.append(parent_idx)
        history_moves.append(move_id)

        if verbose:
            print(depth, state_to_cube_string(T, frontier[0]))

    return False, None, None

def display(state):
    cube_strings = []
    steps = []
    curr = state
    while curr is not None:
        steps = [curr.prev_move] + steps
        cube_strings = [curr.cube_string] + cube_strings
        curr = curr.prev_state
    for step in steps[1:]:
        print(step, " ",end="")
    print("")
    print(len(steps) - 1)
    for i in range(len(steps)):
        if i != 0:
            print(steps[i])
        print(cube_strings[i])

def scrambled(n):
    """Returns a CubeState scrambled over n random moves."""
    state = CubeState()
    for i in range(n):
        state = state.get_random_child()
    return state

table = CubeTables(device)

model = CubeTransformerMoE(d_model=256, n_heads=16, d_ffwd=341, n_layers=8, n_experts=8, n_active=1)
model.load_state_dict(torch.load("/content/drive/MyDrive/cubegpt-3-8a1-t100mpft2-3.pth",
                                 map_location=torch.device("cuda")))
model = model.to(device)
model.eval()
print("")
# 4352021
# 4879125

measure_mse(model)

solved = 0
moves_list = []
for i in range(100):
  print(f"solve #{i+1}", end="")
  starting_state = scrambled(30).cube_string
  solved, solved_state, moves = beam_search_gpu(table, model, starting_state, width=64000, verbose=False, max_moves=30, eval_batch_size=16384)
  print(f" solved: {solved}, moves: {len(moves) if moves else "None"}")
  if solved:
    solved += 1
    moves_list.append(len(moves))

print(np.mean(moves_list))

starting_state = scrambled(30).cube_string
starting_state

solved, solved_state, moves = beam_search_gpu(table, model, starting_state, width=4000, verbose=True, max_moves=30)

display(solved_state)

solved, solved_state, moves = beam_search_gpu(table, model, starting_state, width=16000, verbose=True, max_moves=30)

display(solved_state)

solved, solved_state, moves = beam_search_gpu(table, model, starting_state, width=64000, verbose=True, max_moves=30)

#   ok, solved_state, moves = beam_search_gpu(T, model, scrambled(18).cube_string, width=1000)
#   if ok:
#       display(solved_state)        # your existing display(), unchanged
#       print(moves)                 # ["R", "U2", "F'", ...]  root -> solved